// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Item struct {
	Id   string
	Name string
}

type UpdateItemReq struct {
	Id   string
	Name string
}

type UpdateItemResp struct {
	Code int
	Msg  string
}
