// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type Item struct {
	Id   string
	Name string
}

type UpdateItemReq struct {
	Id   string
	Name string
}

type UpdateItemResp struct {
	Code int
	Msg  string
}

type CaptchaResp struct {
	CaptchaId   string `json:"captcha_id"`
	ImageBase64 string `json:"image_base64"`
}

type SendCodeReq struct {
	Mobile    string `json:"mobile"`
	CaptchaId string `json:"captcha_id"`
	Captcha   string `json:"captcha"`
}

type SendCodeResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type LoginReq struct {
	Mobile string `json:"mobile"`
	Code   string `json:"code"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}
