// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: item.proto

package server

import (
	"context"

	"github.com/zhangxueyao/item/item-rpc/internal/logic"
	"github.com/zhangxueyao/item/item-rpc/internal/svc"
	"github.com/zhangxueyao/item/item-rpc/itemrpc"
)

type ItemServer struct {
	svcCtx *svc.ServiceContext
	itemrpc.UnimplementedItemServer
}

func NewItemServer(svcCtx *svc.ServiceContext) *ItemServer {
	return &ItemServer{
		svcCtx: svcCtx,
	}
}

func (s *ItemServer) GetStock(ctx context.Context, in *itemrpc.GetStockReq) (*itemrpc.GetStockResp, error) {
	l := logic.NewGetStockLogic(ctx, s.svcCtx)
	return l.GetStock(in)
}

func (s *ItemServer) DeductStock(ctx context.Context, in *itemrpc.DeductStockReq) (*itemrpc.DeductStockResp, error) {
	l := logic.NewDeductStockLogic(ctx, s.svcCtx)
	return l.DeductStock(in)
}

func (s *ItemServer) Register(ctx context.Context, in *itemrpc.RegisterReq) (*itemrpc.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *ItemServer) GetUser(ctx context.Context, in *itemrpc.GetUserReq) (*itemrpc.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
