// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: item.proto

package itemrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=Sku,proto3" json:"Sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReq) Reset() {
	*x = GetStockReq{}
	mi := &file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReq) ProtoMessage() {}

func (x *GetStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReq.ProtoReflect.Descriptor instead.
func (*GetStockReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockReq) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

type GetStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=Sku,proto3" json:"Sku,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=Qty,proto3" json:"Qty,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResp) Reset() {
	*x = GetStockResp{}
	mi := &file_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResp) ProtoMessage() {}

func (x *GetStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResp.ProtoReflect.Descriptor instead.
func (*GetStockResp) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockResp) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *GetStockResp) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *GetStockResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeductStockReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           int64                  `protobuf:"varint,1,opt,name=Sku,proto3" json:"Sku,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockReq) Reset() {
	*x = DeductStockReq{}
	mi := &file_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockReq) ProtoMessage() {}

func (x *DeductStockReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockReq.ProtoReflect.Descriptor instead.
func (*DeductStockReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{2}
}

func (x *DeductStockReq) GetSku() int64 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *DeductStockReq) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type DeductStockResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResp) Reset() {
	*x = DeductStockResp{}
	mi := &file_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResp) ProtoMessage() {}

func (x *DeductStockResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResp.ProtoReflect.Descriptor instead.
func (*DeductStockResp) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{3}
}

func (x *DeductStockResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeductStockResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type PayTryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"` // 全局事务ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // 分（正整数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayTryReq) Reset() {
	*x = PayTryReq{}
	mi := &file_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayTryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayTryReq) ProtoMessage() {}

func (x *PayTryReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayTryReq.ProtoReflect.Descriptor instead.
func (*PayTryReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{9}
}

func (x *PayTryReq) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *PayTryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayTryReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayTryReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PayAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayAck) Reset() {
	*x = PayAck{}
	mi := &file_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayAck) ProtoMessage() {}

func (x *PayAck) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayAck.ProtoReflect.Descriptor instead.
func (*PayAck) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{10}
}

func (x *PayAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PayConfirmReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayConfirmReq) Reset() {
	*x = PayConfirmReq{}
	mi := &file_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayConfirmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayConfirmReq) ProtoMessage() {}

func (x *PayConfirmReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayConfirmReq.ProtoReflect.Descriptor instead.
func (*PayConfirmReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{11}
}

func (x *PayConfirmReq) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *PayConfirmReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayConfirmReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayConfirmReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PayCancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xid           string                 `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCancelReq) Reset() {
	*x = PayCancelReq{}
	mi := &file_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCancelReq) ProtoMessage() {}

func (x *PayCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCancelReq.ProtoReflect.Descriptor instead.
func (*PayCancelReq) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{12}
}

func (x *PayCancelReq) GetXid() string {
	if x != nil {
		return x.Xid
	}
	return ""
}

func (x *PayCancelReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayCancelReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PayCancelReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_item_proto protoreflect.FileDescriptor

const file_item_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"item.proto\x12\x04item\"\x1f\n" +
	"\vGetStockReq\x12\x10\n" +
	"\x03Sku\x18\x01 \x01(\x03R\x03Sku\"L\n" +
	"\fGetStockResp\x12\x10\n" +
	"\x03Sku\x18\x01 \x01(\x03R\x03Sku\x12\x10\n" +
	"\x03Qty\x18\x02 \x01(\x03R\x03Qty\x12\x18\n" +
	"\aVersion\x18\x03 \x01(\x03R\aVersion\"8\n" +
	"\x0eDeductStockReq\x12\x10\n" +
	"\x03Sku\x18\x01 \x01(\x03R\x03Sku\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"E\n" +
	"\x0fDeductStockResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"z\n" +
	"\x04User\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\"-\n" +
	"\vRegisterReq\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".item.UserR\x04user\"B\n" +
	"\fRegisterResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\n" +
	"GetUserReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"E\n" +
	"\vGetUserResp\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".item.UserR\x04user\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"i\n" +
	"\tPayTryReq\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"\x18\n" +
	"\x06PayAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"m\n" +
	"\rPayConfirmReq\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"l\n" +
	"\fPayCancelReq\x12\x10\n" +
	"\x03xid\x18\x01 \x01(\tR\x03xid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount2\xe1\x02\n" +
	"\x04Item\x121\n" +
	"\bGetStock\x12\x11.item.GetStockReq\x1a\x12.item.GetStockResp\x12:\n" +
	"\vDeductStock\x12\x14.item.DeductStockReq\x1a\x15.item.DeductStockResp\x121\n" +
	"\bRegister\x12\x11.item.RegisterReq\x1a\x12.item.RegisterResp\x12.\n" +
	"\aGetUser\x12\x10.item.GetUserReq\x1a\x11.item.GetUserResp\x12'\n" +
	"\x06TryPay\x12\x0f.item.PayTryReq\x1a\f.item.PayAck\x12/\n" +
	"\n" +
	"ConfirmPay\x12\x13.item.PayConfirmReq\x1a\f.item.PayAck\x12-\n" +
	"\tCancelPay\x12\x12.item.PayCancelReq\x1a\f.item.PayAckB\vZ\t./itemrpcb\x06proto3"

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData []byte
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)))
	})
	return file_item_proto_rawDescData
}

var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_item_proto_goTypes = []any{
	(*GetStockReq)(nil),     // 0: item.GetStockReq
	(*GetStockResp)(nil),    // 1: item.GetStockResp
	(*DeductStockReq)(nil),  // 2: item.DeductStockReq
	(*DeductStockResp)(nil), // 3: item.DeductStockResp
	(*User)(nil),            // 4: item.User
	(*RegisterReq)(nil),     // 5: item.RegisterReq
	(*RegisterResp)(nil),    // 6: item.RegisterResp
	(*GetUserReq)(nil),      // 7: item.GetUserReq
	(*GetUserResp)(nil),     // 8: item.GetUserResp
	(*PayTryReq)(nil),       // 9: item.PayTryReq
	(*PayAck)(nil),          // 10: item.PayAck
	(*PayConfirmReq)(nil),   // 11: item.PayConfirmReq
	(*PayCancelReq)(nil),    // 12: item.PayCancelReq
}
var file_item_proto_depIdxs = []int32{
	4,  // 0: item.RegisterReq.user:type_name -> item.User
	4,  // 1: item.GetUserResp.user:type_name -> item.User
	0,  // 2: item.Item.GetStock:input_type -> item.GetStockReq
	2,  // 3: item.Item.DeductStock:input_type -> item.DeductStockReq
	5,  // 4: item.Item.Register:input_type -> item.RegisterReq
	7,  // 5: item.Item.GetUser:input_type -> item.GetUserReq
	9,  // 6: item.Item.TryPay:input_type -> item.PayTryReq
	11, // 7: item.Item.ConfirmPay:input_type -> item.PayConfirmReq
	12, // 8: item.Item.CancelPay:input_type -> item.PayCancelReq
	1,  // 9: item.Item.GetStock:output_type -> item.GetStockResp
	3,  // 10: item.Item.DeductStock:output_type -> item.DeductStockResp
	6,  // 11: item.Item.Register:output_type -> item.RegisterResp
	8,  // 12: item.Item.GetUser:output_type -> item.GetUserResp
	10, // 13: item.Item.TryPay:output_type -> item.PayAck
	10, // 14: item.Item.ConfirmPay:output_type -> item.PayAck
	10, // 15: item.Item.CancelPay:output_type -> item.PayAck
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}
